### ISSUE TITLE
ImmSortedSet/Map Slice : min value is incorrect

### ISSUE THREAD

**Issue by scifral** [Imms/Imms#2]
eg:

  var m = ImmSortedMap<int, int>.Empty(Comparer<Int32>.Default);
  foreach (var i in Enumerable.Range(1, 100))
       m = m.Add(i, i);
  var s = m.Slice(30, 60);

The minimum value of the slice is 16 instead of 30. 

In this line of the Slice code: 

    currentRoot = currentRoot.Root_Add(left.Key, left.Value, Comparer, true, Lineage.Immutable);

it looks like left.Key, left.Value should instead be: central.Key, central.Value ?

BTW along with this very useful new Slice operation (thanks!) , it would be great to have efficient public API for iterating a sortedset/map in reverse direction (max to min).

**Comment by GregRos** [comment]
Yes, it should! Oh wow, I wasn't aware anyone was using this. The recently added Slice function hasn't really been tested yet. I really added it just because I felt like it.

Good point about the reverse order. I've actually just came up with a very interesting way of implementing the mixin pattern in C# that should allow me to unify all sorts of implementations, so sortedset/map will have some of the API of `ImmList`. It'll probably have to wait until I finish a website and documentation I'm writing.
